name: s3 deployment workflow

on: 
  push: 
    branches: 
      - master
  workflow_dispatch: 


jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout The Code  
        uses: actions/checkout@v2
      - name: Print Hello world 2
        run: echo "Hello World 2"
        shell: bash
      - name: Print Good bye world 
        run: echo "Good bye"
        shell: bash




      