name: s3 deployment workflow

on: 
  push: 
    branches: 
      - master
  workflow_dispatch: 
  
permissions: 
    id-token: write 
    contents: read

jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout The Code  
        uses: actions/checkout@v2
      - name: Print Hello world 2
        run: echo "Hello World 2"
        shell: bash
      - name: Setup Node js
        uses: actions/setup-node@v3
        with:
          node-version: 18



      
